// In this file you can specify the trial data for your experiment

const trial_info = {
    practice: [
        {
            question: "Are the two objects the same or are they different?",
            item: 1,
            picture: "mental_rotation_images/2_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 2,
            picture: "mental_rotation_images/1_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
         {
            question: "Are the two objects the same or are they different?",
            item: 3,
            picture: "mental_rotation_images/1_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 4,
            picture: "mental_rotation_images/1_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 5,
            picture: "mental_rotation_images/1_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 6,
            picture: "mental_rotation_images/2_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 7,
            picture: "mental_rotation_images/1_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 8,
            picture: "mental_rotation_images/4_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 9,
            picture: "mental_rotation_images/4_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 10,
            picture: "mental_rotation_images/4_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 11,
            picture: "mental_rotation_images/4_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 12,
            picture: "mental_rotation_images/1_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        }
    ],
    
    //Definition of main trails
    main: [
        {
            question: "Are the two objects the same or are they different?",
            item: 1,
            picture: "mental_rotation_images/3_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 2,
            picture: "mental_rotation_images/3_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 3,
            picture: "mental_rotation_images/3_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 5,
            picture: "mental_rotation_images/3_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 6,
            picture: "mental_rotation_images/2_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 7,
            picture: "mental_rotation_images/1_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 8,
            picture: "mental_rotation_images/4_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 9,
            picture: "mental_rotation_images/4_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 10,
            picture: "mental_rotation_images/4_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 11,
            picture: "mental_rotation_images/4_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 12,
            picture: "mental_rotation_images/1_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 13,
            picture: "mental_rotation_images/1_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 14,
            picture: "mental_rotation_images/1_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 15,
            picture: "mental_rotation_images/5_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 16,
            picture: "mental_rotation_images/5_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 17,
            picture: "mental_rotation_images/5_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 18,
            picture: "mental_rotation_images/5_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 19,
            picture: "mental_rotation_images/6_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 20,
            picture: "mental_rotation_images/6_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 21,
            picture: "mental_rotation_images/6_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 22,
            picture: "mental_rotation_images/6_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 23,
            picture: "mental_rotation_images/7_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 24,
            picture: "mental_rotation_images/7_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 25,
            picture: "mental_rotation_images/7_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 26,
            picture: "mental_rotation_images/7_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 27,
            picture: "mental_rotation_images/8_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 28,
            picture: "mental_rotation_images/8_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 29,
            picture: "mental_rotation_images/8_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 30,
            picture: "mental_rotation_images/8_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 31,
            picture: "mental_rotation_images/9_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 32,
            picture: "mental_rotation_images/9_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 33,
            picture: "mental_rotation_images/9_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 34,
            picture: "mental_rotation_images/9_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 35,
            picture: "mental_rotation_images/10_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 36,
            picture: "mental_rotation_images/10_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 37,
            picture: "mental_rotation_images/10_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 38,
            picture: "mental_rotation_images/10_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 39,
            picture: "mental_rotation_images/11_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 40,
            picture: "mental_rotation_images/11_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 41,
            picture: "mental_rotation_images/11_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 42,
            picture: "mental_rotation_images/11_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 43,
            picture: "mental_rotation_images/12_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 44,
            picture: "mental_rotation_images/12_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 45,
            picture: "mental_rotation_images/12_150_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 46,
            picture: "mental_rotation_images/12_150_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '150'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 47,
            picture: "mental_rotation_images/13_50_same.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'same',
            angle: '50'
        },
        {
            question: "Are the two objects the same or are they different?",
            item: 48,
            picture: "mental_rotation_images/13_50_different.jpg",
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            correct: 'different',
            angle: '50'
        },
    ]
};
